#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 11 18:26:39 2018

@author: bhavyababuta
"""

import numpy as np
import pandas as pd

df=pd.read_csv('Churn_Modelling.csv')
data=df.values

x=data[:,:-1]
y=data[:,-1]

X=np.array(x)
Y=np.array(y)

X=X[:,4:13]

X2=np.zeros((X.shape[0],X.shape[1]+2))

#OneHotEncoder , LabelEncoder
for i in range(X.shape[0]):
    if X[i,0]=='France':
        X[i,0]=0
    if X[i,0]=='Spain':
        X[i,0]=1
    if X[i,0]=='Germany':
        X[i,0]=2
    if X[i,1]=='Male':
        X[i,1]=0
    if X[i,1]=='Female':
        X[i,1]=1
    t=X[i,0]
    X2[i,t]=1
X2[:,3:11]=X[:,1:10]

import keras
from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()
classifier.add(Dense(output_dim=6,activation='reLU'))

